version: "3"

services:
  nacos:
    build:
      context: .
      dockerfile: ./Dockerfile-nacos
    container_name: nacos
    ports:
      - "8848:8848"
    restart: always
    entrypoint: ./wait-for-it.sh mysql:3306 -t 0 -- bin/docker-startup.sh
    depends_on:
      - mysql
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=Japan
    networks:
      - online-education
  seata:
    image: seataio/seata-server:1.3.0
    container_name: seata
    hostname: seata-server
    restart: always
    depends_on:
      - mysql
      - nacos
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./doc/seata/config:/root/seata-config
    networks:
      - online-education
  mysql:
    image: mysql:8.0.22
    restart: always
    container_name: mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./doc/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - online-education
  sentinel:
    image: bladex/sentinel-dashboard:latest
    restart: on-failure:3
    container_name: sentinel_dashboard
    ports:
      - "8858:8858"
    networks:
      - online-education
  rabbitmq:
    image: rabbitmq:3.8.19-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=andochiwa
      - RABBITMQ_DEFAULT_PASS=123789
    networks:
      - online-education
  redis:
    image: redis:6.2.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - online-education
  api_gateway:
    build:
      context: .
      dockerfile: ./infrastructure/api_gateway80/Dockerfile
    container_name: api_gateway80
    command: ./wait-for-it.sh nacos:8848 -t 0 -- java -jar api_gateway.jar
    depends_on:
      - mysql
      - nacos
    restart: always
    ports:
      - "80:80"
    networks:
      - online-education
  service_edu:
    build:
      context: .
      dockerfile: ./service/service_edu8001/Dockerfile
    container_name: service_edu8001
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_edu.jar
    depends_on:
      - mysql
      - nacos
      - rabbitmq
      - redis
      - seata
    restart: always
    ports:
      - "8001:8001"
    networks:
      - online-education
  service_oss:
    build:
      context: .
      dockerfile: ./service/service_oss8002/Dockerfile
    container_name: service_oss8002
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_oss.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
    restart: always
    ports:
      - "8002:8002"
    networks:
      - online-education
  service_vod:
    build:
      context: .
      dockerfile: ./service/service_vod8003/Dockerfile
    container_name: service_vod8003
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_vod.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
      - rabbitmq
    restart: always
    ports:
      - "8003:8003"
    networks:
      - online-education
  service_cms:
    build:
      context: .
      dockerfile: ./service/service_cms8004/Dockerfile
    container_name: service_cms8004
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_cms.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
    restart: always
    ports:
      - "8004:8004"
    networks:
      - online-education
  service_center:
    build:
      context: .
      dockerfile: ./service/service_center8005/Dockerfile
    container_name: service_center8005
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_center.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
      - rabbitmq
    restart: always
    ports:
      - "8005:8005"
    networks:
      - online-education
  service_order:
    build:
      context: .
      dockerfile: ./service/service_order8006/Dockerfile
    container_name: service_order8006
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_order.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
      - rabbitmq
    restart: always
    ports:
      - "8006:8006"
    networks:
      - online-education
  service_statistic:
    build:
      context: .
      dockerfile: ./service/service_statistic8007/Dockerfile
    container_name: service_statistic8007
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_statictis.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
      - rabbitmq
    restart: always
    ports:
      - "8007:8007"
    networks:
      - online-education
  service_acl:
    build:
      context: .
      dockerfile: ./service/service_acl8008/Dockerfile
    container_name: service_acl8008
    command: ./wait-for-it.sh nacos:8848 -t 0 -- ./wait-for-it.sh seata:8091 -t 0 -- java -jar service_acl.jar
    depends_on:
      - mysql
      - nacos
      - redis
      - seata
    restart: always
    ports:
      - "8008:8008"
    networks:
      - online-education

networks:
  online-education:
